spring:
  application:
    name: ebuy-address-service
  datasource:
    url: jdbc:postgresql://ec2-34-235-108-68.compute-1.amazonaws.com/d19soagqjkfjek
    username: ejzawtsprusxzs
    password: 73103de540ca1cecbf15ea66d7d6080bc7a8668b984a510b4749e9560930933c
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  jackson:
    serialization:
      indent_output : true
eureka:
  client:
    service-url:
      defaultZone: https://ebuy-registry-service.herokuapp.com/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
